name: foxrivercatering
favicon: null
layout_spectrum: 0.92317
typography_spectrum: 0.8040835214778781
title: Fox River Catering
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#280000'
    - '#6ca8e6'
    - '#fd006a'
    - '#8b9f00'
    - '#fefefb'
  brandStrength: 0.7729181731119752
  lightness: 0.6702858256176114
  saturation: 0.23170838435180485
  rhythmicContrast: 0.8203592547215521
purpose: []
